## *********************************************************
##
## File autogenerated for the kinect2_tracker package
## by the dynamic_reconfigure package.
## Please do not edit.
##
## ********************************************************/

from dynamic_reconfigure.encoding import extract_params

inf = float('inf')

config_description = {'upper': 'DEFAULT', 'lower': 'groups', 'srcline': 245, 'name': 'Default', 'parent': 0, 'srcfile': '/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py', 'cstate': 'true', 'parentname': 'Default', 'class': 'DEFAULT', 'field': 'default', 'state': True, 'parentclass': '', 'groups': [{'upper': 'KINECT_V2_INITIAL_VALUE', 'lower': 'kinect_v2_initial_value', 'srcline': 124, 'name': 'Kinect_v2_initial_value', 'parent': 0, 'srcfile': '/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py', 'cstate': 'true', 'parentname': 'Default', 'class': 'DEFAULT::KINECT_V2_INITIAL_VALUE', 'field': 'DEFAULT::kinect_v2_initial_value', 'state': True, 'parentclass': 'DEFAULT', 'groups': [], 'parameters': [{'srcline': 10, 'description': 'Predkosc', 'max': 1.0, 'cconsttype': 'const double', 'ctype': 'double', 'srcfile': '/home/lukasz/catkin_interfejs/src/kinect_v2/kinect2_tracker/cfg/set_kinect_v2.cfg', 'name': 'velocity', 'edit_method': '', 'default': 0.4, 'level': 0, 'min': 0.0, 'type': 'double'}, {'srcline': 11, 'description': 'Szerokosc strefy martwej', 'max': 1.0, 'cconsttype': 'const double', 'ctype': 'double', 'srcfile': '/home/lukasz/catkin_interfejs/src/kinect_v2/kinect2_tracker/cfg/set_kinect_v2.cfg', 'name': 'strefa', 'edit_method': '', 'default': 0.2, 'level': 0, 'min': 0.0, 'type': 'double'}], 'type': '', 'id': 1}], 'parameters': [], 'type': '', 'id': 0}

min = {}
max = {}
defaults = {}
level = {}
type = {}
all_level = 0

#def extract_params(config):
#    params = []
#    params.extend(config['parameters'])
#    for group in config['groups']:
#        params.extend(extract_params(group))
#    return params

for param in extract_params(config_description):
    min[param['name']] = param['min']
    max[param['name']] = param['max']
    defaults[param['name']] = param['default']
    level[param['name']] = param['level']
    type[param['name']] = param['type']
    all_level = all_level | param['level']

